### ISSUE TITLE
when i use dpm-solver，cuda out of memory

### ISSUE THREAD

**Issue by zhao9chen99999** [KidsWithTokens/MedSegDiff#49]
i looked other's issue,someone said need to change the pytorch version to 1.8.1,but when i try it it won't work,i also tried other version of pytorch still won't work

**Comment by zhao9chen99999** [comment]
i wonder if i used the correct version of pytorch, or what mistake did i make?

**Comment by zhao9chen99999** [comment]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/57703720/223636332-1f4026c5-0e73-453d-943c-280a5ea20b8d.png">
each of these steps increase about 2000mbGPU memory,and then：
<img width="565" alt="image" src="https://user-images.githubusercontent.com/57703720/223636773-c2db81e9-5b39-4ba7-8502-67b374b95f06.png">

**Comment by jaceqin** [comment]
我sample没有出现这个问题

**Comment by jaceqin** [comment]
> <img alt="image" width="252" src="https://user-images.githubusercontent.com/57703720/223636332-1f4026c5-0e73-453d-943c-280a5ea20b8d.png">
> 
> each of these steps increase about 2000mbGPU memory,and then：
> <img alt="image" width="565" src="https://user-images.githubusercontent.com/57703720/223636773-c2db81e9-5b39-4ba7-8502-67b374b95f06.png">

能加你联系方式讨论下吗

**Comment by zhao9chen99999** [comment]
> > <img alt="image" width="252" src="https://user-images.githubusercontent.com/57703720/223636332-1f4026c5-0e73-453d-943c-280a5ea20b8d.png">
> > each of these steps increase about 2000mbGPU memory,and then：
> > <img alt="image" width="565" src="https://user-images.githubusercontent.com/57703720/223636773-c2db81e9-5b39-4ba7-8502-67b374b95f06.png">
> 
> 能加你联系方式讨论下吗

好的，加个微信吗？

**Comment by zhao9chen99999** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/57703720/223894880-982b8b3b-a875-4621-98cf-9af784ef8034.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/57703720/223894920-e3feaa10-6328-4618-8485-8cabf2e0d8b3.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/57703720/223894954-54a002e5-2725-478d-9918-82bea378aea7.png">
i got these errors when i sampling on my own dataset

**Comment by jaceqin** [comment]
> <img alt="image" width="547" src="https://user-images.githubusercontent.com/57703720/223894880-982b8b3b-a875-4621-98cf-9af784ef8034.png">
> 
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/57703720/223894920-e3feaa10-6328-4618-8485-8cabf2e0d8b3.png">
> 
> <img alt="image" width="418" src="https://user-images.githubusercontent.com/57703720/223894954-54a002e5-2725-478d-9918-82bea378aea7.png">
> 
> i got these errors when i sampling on my own dataset

这个是正常的停止，就是sample结束

**Comment by Sunny599** [comment]
请问问题解决了吗，我遇到了相同的问题。当使用dpm-solver：RuntimeError: CUDA out of memory。同求微信交流

**Comment by zhao9chen99999** [comment]
> 请问问题解决了吗，我遇到了相同的问题。当使用dpm-solver：RuntimeError: CUDA out of memory。同求微信交流

dpm的问题还是没有解决，你留个微信吧，我加你

**Comment by maomaocun** [comment]
同求微信
建个群玩玩吗

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！

**Comment by WuJunde** [comment]
Could anyone adds me to your WeChat group? I can occasionally answer some questions in the group. thanks

**Comment by maomaocun** [comment]
我的微信19162076385

**Comment by pangpangjy** [comment]
请问大家解决这个问题了嘛？我也出现了这个问题，希望有机会交流一下

**Comment by pangpangjy** [comment]
请问大家解决这个问题了嘛？我也出现了这个问题，希望有机会交流一下

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！

**Comment by Browny323** [comment]
我也遇到了这个问题，请问最后是怎样解决的呢？

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！

**Comment by WuJunde** [comment]
@zhao9chen99999 @Browny323 This problem has been solved by @lin-tianyu through detaching the sample out the gradient graph. If you're still experiencing this issue, please give it a try. Thank you.

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！
